version: "3.7"
services:
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    network_mode: bridge
#    volumes:
#      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./simplenutritionfrontend3/
#    ports:
#    - 80:80
#    - 10000:10000


  quasar_nginx:
    container_name: quasar_nginx
    build:
      context: ../simplenutritionfrontend3
      dockerfile: ../simplenutritionfrontend3/Dockerfile

    ports:
      - 80:80



#  frontend:
#    container_name: frontend
#    build:
#      context: simplenutritionfrontend3
#      dockerfile: Dockerfile
#    working_dir: /frontend
#    ports:
#      - 8081:8081



  db:
    hostname: ${DATABASE_HOST}
    container_name: ${CONTAINER_NAME}
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - ../.env

#
  django:
    container_name: django_api
    restart: always
    build:
      context: ../Django
      dockerfile: ../Django/Dockerfile
    command: bash -c "./Django/entryPoint.sh"
    volumes:
      - .:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
    env_file:
      - ../.env

  go:
    container_name: go_api
    restart: always
    build:
      context: ../go_api
      dockerfile: ../go_api/Dockerfile.debug
      args:
        API_PORT: ${GO_PORT}
    volumes:
    - .:/dockerdev
    ports:
    - "${GO_PORT}:${GO_PORT}"
    - 40000:40000
    depends_on:
      - db
    env_file:
      - ../.env