create table nutrients_nutrient
(
    id                     int auto_increment
        primary key,
    nameFr                 varchar(255)   not null,
    nameEn                 varchar(255)   not null,
    unit                   varchar(50)    null,
    besoin                 varchar(255)   not null,
    sportivAdditionnalNeed int            null,
    nutrientGroupTitle     tinyint(1)     not null,
    needPerKg              tinyint(1)     null,
    nutrientGroup_id       int            null,
    familiarNameFr         varchar(255)   not null,
    besoinMax              varchar(255)   not null,
    max                    decimal(10, 5) null,
    menNeed                decimal(10, 5) null,
    womenNeed              decimal(10, 5) null,
    code                   varchar(255)   null,
    constraint nutrients_nutrient_nutrientGroup_id_1999103e_fk_nutrients
        foreign key (nutrientGroup_id) references nutrients_nutrientgroup (id)
);

create index nutrients_nutrient_unit_40d5a0c6
    on nutrients_nutrient (unit);

INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (203, 'PROTÉINES', 'PROTEIN', 'g', '0', null, 1, 0, 3, '', '0', null, null, null, 'PROT');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (204, 'LIPIDES TOTAUX', 'FAT (TOTAL LIPIDS)', 'g', '0', null, 1, 0, 2, 'Lipides', '0', null, null, null, 'LIP');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (205, 'GLUCIDES TOTAUX (PAR DIFFÉRENCE)', 'CARBOHYDRATE, TOTAL (BY DIFFERENCE)', 'g', '0', null, 1, 0, 1, 'Glucides', '0', null, null, null, 'GLU');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (207, 'CENDRES, TOTALES', 'ASH, TOTAL', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (208, 'Calories', 'Calories', 'Cal', '0', null, 1, 0, 9, 'Calories', '0', null, null, null, 'CAL');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (210, 'SUCROSE', 'SUCROSE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (211, 'GLUCOSE', 'GLUCOSE', 'g', '0', null, 0, 0, 1, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (212, 'FRUCTOSE', 'FRUCTOSE', 'g', '0', null, 0, 0, 1, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (213, 'LACTOSE', 'LACTOSE', 'g', '0', null, 0, 0, 1, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (214, 'MALTOSE', 'MALTOSE', 'g', '0', null, 0, 0, 1, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (221, 'ALCOOL', 'ALCOHOL', 'g', '0', null, 0, 0, 1, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (245, 'ACIDE OXALIQUE', 'OXALIC ACID', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (255, 'EAU', 'MOISTURE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (260, 'MANNITOL', 'MANNITOL', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (261, 'SORBITOL', 'SORBITOL', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (262, 'CAFÉINE', 'CAFFEINE', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (263, 'THÉOBROMINE', 'THEOBROMINE', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (268, 'ÉNERGIE (KILOJOULES)', 'ENERGY (KILOJOULES)', 'kJ', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (269, 'SUCRES TOTAUX', 'SUGARS, TOTAL', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (287, 'GALACTOSE', 'GALACTOSE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (291, 'FIBRES ALIMENTAIRES TOTALES', 'FIBRE, TOTAL DIETARY', 'g', '0', null, 1, 0, 8, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (301, 'CALCIUM', 'CALCIUM', 'mg', '700', 800, 0, 0, 5, '', '0', null, null, null, 'Ca');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (303, 'FER', 'IRON', 'mg', '14', 0, 0, 0, 5, '', '0', null, null, null, 'Fe');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (304, 'MAGNÉSIUM', 'MAGNESIUM', 'mg', '500', 0, 0, 0, 5, '', '0', null, null, null, 'Mg');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (305, 'PHOSPHORE', 'PHOSPHORUS', 'mg', '750', null, 0, 0, 5, '', '0', null, null, null, 'P');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (306, 'POTASSIUM', 'POTASSIUM', 'mg', '3100', null, 0, 0, 5, '', '0', null, null, null, 'K');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (307, 'SODIUM', 'SODIUM', 'mg', '2400', null, 0, 0, 5, '', '0', null, null, null, 'Na');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (309, 'ZINC', 'ZINC', 'mg', '12', null, 0, 0, 5, '', '0', null, null, null, 'Zn');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (312, 'CUIVRE', 'COPPER', 'mg', '2', 2, 0, 0, 5, '', '0', null, null, null, 'Cu');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (315, 'MANGANÈSE', 'MANGANESE', 'mg', '2.8', 0, 0, 0, 5, '', '0', null, null, null, 'Mn');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (317, 'SÉLÉNIUM', 'SELENIUM', 'µg', '60', null, 0, 0, 5, '', '0', null, null, null, 'Se');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (319, 'RÉTINOL', 'RETINOL', 'µg', '800', null, 0, 0, null, '', '0', null, null, null, 'VIT A');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (321, 'BÉTA CAROTÈNE', 'BETA CAROTENE', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (323, 'ALPHA-TOCOPHÉROL', 'ALPHA-TOCOPHEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (324, 'VITAMINE D (UNITES INTERNATIONALES)', 'VITAMIN D (INTERNATIONAL UNITS)', 'IU', '0', null, 0, 0, null, 'vitamine D', '0', null, null, null, 'VIT D');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (339, 'VITAMINE D (D2 + D3)', 'VITAMIN D (D2 + D3)', 'µg', '10', null, 0, 0, 4, 'vitamine D', '0', null, null, null, 'VIT D');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (401, 'VITAMINE C', 'VITAMIN C', 'mg', '110', null, 0, 0, 4, '', '0', null, null, null, 'VIT C');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (404, 'THIAMINE', 'THIAMIN', 'mg', '1.1', null, 0, 0, 4, 'vitamine B1', '0', null, null, null, 'VIT B1');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (405, 'RIBOFLAVINE', 'RIBOFLAVIN', 'mg', '1.4', null, 0, 0, 4, 'vitamine B2', '0', null, null, null, 'VIT B2');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (406, 'NIACINE (ACIDE NICOTINIQUE) PRÉFORMÉE', 'NIACIN (NICOTINIC ACID) PREFORMED', 'mg', '16', null, 0, 0, 4, 'vitamine B3', '0', null, null, null, 'VIT B3');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (409, 'ÉQUIVALENT EN NIACINE TOTALE', 'TOTAL NIACIN EQUIVALENT', 'NE', '0', null, 0, 0, null, '', '0', null, null, null, 'VIT B3');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (410, 'ACIDE PANTOTHÉNIQUE', 'PANTOTHENIC ACID', 'mg', '6', null, 0, 0, 4, 'vitamine B5', '0', null, null, null, 'VIT B5');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (415, 'VITAMINE B-6', 'VITAMIN B-6', 'mg', '1.4', null, 0, 0, 4, 'vitamine B6', '0', null, null, null, 'VIT B6');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (416, 'BIOTINE', 'BIOTIN', 'µg', '50', null, 0, 0, null, 'vitamine B8', '0', null, null, null, 'VIT B8');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (417, 'FOLACINE TOTALE', 'TOTAL FOLACIN', 'µg', '500', null, 0, 0, 4, 'vitamine B9', '0', null, null, null, 'VIT B9');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (418, 'VITAMINE B-12', 'VITAMIN B-12', 'µg', '2.5', null, 0, 0, 4, 'vitamine B12', '0', null, null, null, 'VIT B12');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (430, 'VITAMINE K', 'VITAMIN K', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, 'VIT K');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (431, 'ACIDE FOLIQUE', 'FOLIC ACID', 'µg', '500', null, 0, 0, null, 'vitamine C', '0', null, null, null, 'BVIT 9');
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (501, 'TRYPTOPHANE', 'TRYPTOPHAN', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (502, 'THRÉONINE', 'THREONINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (503, 'ISOLEUCINE', 'ISOLEUCINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (504, 'LEUCINE', 'LEUCINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (505, 'LYSINE', 'LYSINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (506, 'MÉTHIONINE', 'METHIONINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (507, 'CYSTINE', 'CYSTINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (508, 'PHÉNYLALANINE', 'PHENYLALANINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (509, 'TYROSINE', 'TYROSINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (510, 'VALINE', 'VALINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (511, 'ARGININE', 'ARGININE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (512, 'HISTIDINE', 'HISTIDINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (513, 'ALANINE', 'ALANINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (514, 'ACIDE ASPARTIQUE', 'ASPARTIC ACID', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (515, 'ACIDE GLUTAMIQUE', 'GLUTAMIC ACID', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (516, 'GLYCINE', 'GLYCINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (517, 'PROLINE', 'PROLINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (518, 'SERINE', 'SERINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (550, 'ASPARTAME', 'ASPARTAME', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (601, 'CHOLESTEROL', 'CHOLESTEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (605, 'ACIDES GRAS TRANS TOTAUX', 'FATTY ACIDS, TRANS, TOTAL', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (606, 'ACIDES GRAS SATURÉS TOTAUX', 'FATTY ACIDS, SATURATED, TOTAL', 'g', '0', null, 0, 0, 2, 'saturés', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (607, 'ACIDES GRAS SATURÉS, 4:0, BUTANOÏQUE', 'FATTY ACIDS, SATURATED, 4:0, BUTANOIC', 'g', '0', null, 0, 0, 2, '4:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (608, 'ACIDES GRAS SATURÉS, 6:0, HEXANOÏQUE', 'FATTY ACIDS, SATURATED, 6:0, HEXANOIC', 'g', '0', null, 0, 0, 2, '6:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (609, 'ACIDES GRAS SATURÉS, 8:0, OCTANOÏQUE', 'FATTY ACIDS, SATURATED, 8:0, OCTANOIC', 'g', '0', null, 0, 0, 2, '8:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (610, 'ACIDES GRAS SATURÉS, 10:0, DÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 10:0, DECANOIC', 'g', '0', null, 0, 0, 2, '10:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (611, 'ACIDES GRAS SATURÉS, 12:0, DODÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 12:0, DODECANOIC', 'g', '0', null, 0, 0, 2, '12:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (612, 'ACIDES GRAS SATURÉS, 14:0, TÉTRADÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 14:0, TETRADECANOIC', 'g', '0', null, 0, 0, 2, '14:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (613, 'ACIDES GRAS SATURÉS, 16:0, HEXADÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 16:0, HEXADECANOIC', 'g', '0', null, 0, 0, 2, '16:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (614, 'ACIDES GRAS SATURÉS, 18:0,  OCTADÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 18:0, OCTADECANOIC', 'g', '0', null, 0, 0, 2, '18:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (615, 'ACIDES GRAS SATURÉS, 20:0, EÏCOSANOÏQUE', 'FATTY ACIDS, SATURATED, 20:0, EICOSANOIC', 'g', '0', null, 0, 0, 2, '20:0', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (617, 'ACIDES GRAS MONOINSATURÉS, 18:1non différencié, OCTADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 18:1undifferentiated, OCTADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (618, 'ACIDES GRAS POLYINSATURÉS, 18:2non différencié,  LINOLÉIQUE, OCTADÉCADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:2undifferentiated, LINOLEIC, OCTADECADIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (619, 'ACIDES GRAS POLYINSATURÉS, 18:3non différencié, LINOLÉNIQUE, OCTADÉCATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:3undifferentiated, LINOLENIC, OCTADECATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (620, 'ACIDES GRAS POLYINSATURÉS, 20:4, EÏCOSATÉTRAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:4, EICOSATETRAENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (621, 'ACIDES GRAS POLYINSATURÉS,  22:6 n-3, DOCOSAHEXAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 22:6 n-3, DOCOSAHEXAENOIC (DHA)', 'g', '0.25', null, 0, 0, 2, 'omega3, DHA', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (624, 'ACIDES GRAS SATURÉS, 22:0, DOCOSANOÏQUE', 'FATTY ACIDS, SATURATED, 22:0, DOCOSANOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (625, 'ACIDES GRAS MONOINSATURÉS, 14:1, TÉTRADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 14:1, TETRADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (626, 'ACIDES GRAS MONOINSATURÉS, 16:1non différencié, HEXADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 16:1undifferentiated, HEXADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (627, 'ACIDES GRAS POLYINSATURÉS, 18:4, OCTADÉCATÉTRAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:4, OCTADECATETRAENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (628, 'ACIDES GRAS MONOINSATURÉS, 20:1, EÏCOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 20:1, EICOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (629, 'ACIDES GRAS POLYINSATURÉS, 20:5 n-3, EÏCOSAPENTAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:5 n-3, EICOSAPENTAENOIC (EPA)', 'g', '0.25', null, 0, 0, 2, 'omega3, EPA', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (630, 'ACIDES GRAS MONOINSATURÉS, 22:1non différencié, DOCOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 22:1undifferentiated, DOCOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (631, 'ACIDES GRAS POLYINSATURÉS, 22:5 n-3, DOCOSAPENTAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 22:5 n-3, DOCOSAPENTAENOIC (DPA)', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (636, 'STÉROLS VÉGÉTAUX TOTAUX', 'TOTAL PLANT STEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (638, 'STIGMASTÉROL', 'STIGMASTEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (645, 'ACIDES GRAS MONOINSATURÉS  TOTAUX', 'FATTY ACIDS, MONOUNSATURATED, TOTAL', 'g', '0', null, 0, 0, 2, 'mono-insaturés', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (646, 'ACIDES GRAS POLYINSATURÉS TOTAUX', 'FATTY ACIDS, POLYUNSATURATED, TOTAL', 'g', '0', null, 0, 0, 2, 'poly-insaturés', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (652, 'ACIDES GRAS SATURÉS, 15:0, PENTADÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 15:0, PENTADECANOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (653, 'ACIDES GRAS SATURÉS, 17:0, HEPTADÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 17:0, HEPTADECANOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (654, 'ACIDES GRAS SATURÉS, 24:0, TÉTRASANOÏQUE', 'FATTY ACIDS, SATURATED, 24:0, TETRACOSANOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (802, 'MONOSACCHARIDES TOTAUX', 'TOTAL MONOSACCARIDES', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (803, 'DISACCHARIDES TOTAUX', 'TOTAL DISACCHARIDES', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (806, 'FOLATES PRÉSENTS NATURELLEMENT', 'NATURALLY OCCURRING FOLATE', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (810, 'AMIDON', 'STARCH', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (811, 'BÊTA-TOCOPHÉROL', 'BETA-TOCOPHEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (812, 'GAMMA-TOCOPHÉROL', 'GAMMA-TOCOPHEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (813, 'DELTA-TOCOPHÉROL', 'DELTA-TOCOPHEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (814, 'ÉQUIVALENTS D''ACTIVITÉ DU RÉTINOL', 'RETINOL ACTIVITY EQUIVALENTS', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (815, 'ÉQUIVALENTS DE FOLATE ALIMENTAIRE (ÉFA)', 'DIETARY FOLATE EQUIVALENTS', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (816, 'BÉTA-SITOSTÉROL', 'BETA-SITOSTEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (817, 'ACIDES GRAS MONOINSATURÉS, 16:1t, HEXADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 16:1t, HEXADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (818, 'ACIDE GRAS MONOINSATURÉS, 18:1t, OCTADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 18:1t, OCTADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (819, 'ACIDES GRAS POLYINSATURÉS, 18:2i, LINOLÉIQUE, OCTADÉCADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:2i, LINOLEIC, OCTADECADIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (820, 'ACIDES GRAS MONOINSATURÉS, 24:1c, TÉTRACOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 24:1c, TETRACOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (821, 'ACIDES GRAS MONOINSATURÉS, 16:1c, HEXADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 16:1c, HEXADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (823, 'ACIDES GRAS POLYINSATURÉS, 20:2 c,c  EÏCOSADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:2 c,c  EICOSADIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (824, 'ACIDES GRAS MONOINSATURÉS, 18:1c, OCTADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 18:1c, OCTADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (825, 'ACIDES GRAS POLYINSATURÉS, 18:2 c,c n-6, LINOLÉIQUE, OCTADÉCADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:2 c,c n-6,  LINOLEIC, OCTADECADIENOIC', 'g', '0', null, 0, 0, 2, 'omega6, linoléique', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (826, 'ACIDES GRAS MONOINSATURÉS, 17:1, HEPTADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 17:1, HEPTADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (827, 'ACIDES GRAS POLYINSATURÉS, 20:3, EÏCOSATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:3, EICOSATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (828, 'HYDROXYPROLINE', 'HYDROXYPROLINE', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (829, 'ACIDES GRAS TRANS MONOÉNOÏQUES TOTAUX', 'FATTY ACIDS, TOTAL TRANS-MONOENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (830, 'ACIDES GRAS SATURÉS, 13:0, TRIDÉCANOÏQUE', 'FATTY ACIDS, SATURATED, 13:0 TRIDECANOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (831, 'ACIDES GRAS POLYINSATURÉS, 18:3 c,c,c  n-3, LINOLÉNIQUE, OCTADÉCATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:3 c,c,c n-3  LINOLENIC, OCTADECATRIENOIC', 'g', '0', null, 0, 0, 2, 'omega3, linolénique', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (832, 'ACIDES GRAS POLYINSATURÉS, 18:3 c,c,c n-6, g-LINOLÉNIQUE, OCTADÉCATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:3 c,c,c n-6, g-LINOLENIC, OCTADECATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (833, 'ACIDES GRAS MONOINSATURÉS, 15:1, PENTADÉCÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 15:1, PENTADECENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (834, 'ALPHA-CAROTÈNE', 'ALPHA CAROTENE', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (835, 'BÊTA-CRYPTOZANTHINE', 'BETA CRYPTOXANTHIN', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (836, 'LYCOPÈNE', 'LYCOPENE', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (837, 'LUTÉINE ET ZÉAXANTHINE', 'LUTEIN AND ZEAXANTHIN', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (838, 'ACIDES GRAS POLYINSATURÉS CONJUGUÉS, 18:2 cla, LINOLÉIQUE, OCTADÉCADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, CONJUGATED, 18:2 cla, LINOLEIC, OCTADECADIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (840, 'ACIDES GRAS MONOINSATURÉS, 22:1c, DOCOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 22:1c, DOCOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (841, 'ACIDES GRAS POLYINSATURÉS, 18:3i, LINOLÉNIQUE, OCTADÉCATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:3i, LINOLENIC, OCTADECATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (843, 'ACIDES GRAS POLYINSATURÉS,  21:5', 'FATTY ACIDS, POLYUNSATURATED, 21:5', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (845, 'ACIDES GRAS POLYINSATURÉS, 22:4n-6, DOCOSATÉTRAÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 22:4 n-6, DOCOSATETRAENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (846, 'ACIDES GRAS MONOINSATURÉS, 24:1non différencié, TÉTRACOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED,  24:1undifferentiated, TETRACOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (847, 'ACIDES GRAS MONOINSATURÉS, 12:1, LAUROLEIC', 'FATTY ACIDS, MONOUNSATURATED, 12:1, LAUROLEIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (848, 'ACIDES GRAS POLYINSATURÉS, 22:3', 'FATTY ACIDS, POLYUNSATURATED, 22:3,', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (849, 'ACIDES GRAS POLYINSATURÉS, 22:2, DOCOSADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 22:2, DOCOSADIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (852, 'ACIDE GRAS MONOINSATURÉS, 22:1t, DOCOSÉNOÏQUE', 'FATTY ACIDS, MONOUNSATURATED, 22:1t, DOCOSENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (853, 'ACIDES GRAS POLYINSATURÉS, 18:2t,t , OCTADECADIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 18:2t,t , OCTADECADIENENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (854, 'ACIDES GRAS POLYINSATURÉS, 20:3 n-6, EÏCOSATRIÉNOÏQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:3 n-6, EICOSATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (855, 'ACIDES GRAS POLYINSATURÉS, 20:4 n-6, ARACHIDONIQUE', 'FATTY ACIDS, POLYUNSATURATED, 20:4 n-6, ARACHIDONIC', 'g', '0', null, 0, 0, 2, 'omega6, arachidonique', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (859, 'ACIDES GRAS TRANS POLYÉNOÏQUES TOTAUX', 'FATTY ACIDS, TOTAL TRANS-POLYENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (861, 'ACIDES GRAS POLYINSATURÉS, 20:3 n-3', 'FATTY ACIDS, POLYUNSATURATED, 20:3 n-3 EICOSATRIENOIC', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (862, 'CHOLINE, TOTALE', 'CHOLINE, TOTAL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (863, 'BÉTAÏNE', 'BETAINE', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (866, 'CAMPESTÉROL', 'CAMPESTEROL', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (868, 'ACIDES GRAS POLYINSATURÉS, TOTAUX D''OMÉGA N-3
', 'FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA  N-3', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (869, 'ACIDES GRAS POLYINSATURÉS, TOTAUX D''OMÉGA N-6', 'FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA   N-6', 'g', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (874, 'VITAMINE B12, AJOUTÉE', 'VITAMIN B12, ADDED', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (875, 'ALPHA-TOCOPHÉROL, AJOUTÉ', 'ALPHA-TOCOPHEROL, ADDED', 'mg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (876, 'VITAMINE D2, (ERGOCALCIFÉROL)', 'VITAMIN D2, ERGOCALCIFEROL', 'µg', '0', null, 0, 0, null, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (1001, 'Vitamines', 'Vitamins', '%', '0', null, 1, 0, 4, '', '0', null, null, null, null);
INSERT INTO simplenutrition.nutrients_nutrient (id, nameFr, nameEn, unit, besoin, sportivAdditionnalNeed, nutrientGroupTitle, needPerKg, nutrientGroup_id, familiarNameFr, besoinMax, max, menNeed, womenNeed, code) VALUES (1002, 'Minéraux', 'Minerals', '%', '0', null, 1, 0, 5, '', '0', null, null, null, null);