# Generated by Django 2.2.4 on 2020-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
