# Generated by Django 2.2.4 on 2020-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.IntegerField(default=1),
        ),
    ]
