# Generated by Django 2.2.4 on 2020-09-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200705_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carbohydrateProportion',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fatProportion',
            field=models.FloatField(default=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proteinProportion',
            field=models.FloatField(default=15),
        ),
    ]
