# Generated by Django 3.1.1 on 2020-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200913_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonyme_account',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_adress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='poid',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taille',
            field=models.IntegerField(default=175),
        ),
    ]
