# Generated by Django 3.1.1 on 2021-02-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201217_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
