# Generated by Django 3.1.1 on 2021-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code_forget_password',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
