# Generated by Django 2.2.4 on 2020-03-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name_fr',
            field=models.CharField(default='food_name_fr', max_length=253),
        ),
    ]
