# Generated by Django 2.2.4 on 2020-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_conversionfactor_conversion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionfactor',
            name='conversion_factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
