# Generated by Django 2.2.4 on 2020-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_conversionfactor_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionfactor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
