# Generated by Django 2.2.4 on 2020-05-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20200301_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgroup',
            name='date_created',
        ),
    ]
