# Generated by Django 2.2.4 on 2020-09-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_food_nb_of_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alim_group_level', models.CharField(max_length=150)),
                ('grp_code', models.CharField(max_length=150)),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.FoodGroup')),
            ],
        ),
    ]
