# Generated by Django 2.2.4 on 2020-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_auto_20200911_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='nb_of_selection',
            field=models.IntegerField(default=0),
        ),
    ]
