# Generated by Django 2.2.4 on 2020-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_auto_20200911_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionfactor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
