# Generated by Django 3.1.1 on 2020-09-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_auto_20200911_1816'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name_fr'], name='foods_food_name_fr_ee1c37_idx'),
        ),
    ]
