# Generated by Django 2.2.4 on 2020-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_routine_meal',
            name='consumption_hour',
            field=models.IntegerField(default=0),
        ),
    ]
