# Generated by Django 2.2.4 on 2020-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_link_routine_meal_consumption_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_routine_meal',
            name='duration_hour',
        ),
        migrations.RemoveField(
            model_name='link_routine_meal',
            name='start_hour',
        ),
    ]
