# Generated by Django 2.2.4 on 2020-09-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0009_food_nb_of_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFr', models.CharField(default='nutrient_name_fr_default', max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
                ('unit', models.SlugField(null=True)),
                ('besoin', models.CharField(default=0, max_length=255)),
                ('sportivAdditionnalNeed', models.IntegerField(default=0, null=True)),
                ('nutrientGroupTitle', models.BooleanField(default=False)),
                ('needPerKg', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFr', models.CharField(default='', max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
                ('deployed_default', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.BooleanField(default=False, null=True)),
                ('nutrient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nutrients.Nutrient')),
                ('nutrientGroup', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nutrients.NutrientGroup')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='nutrientGroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nutrients.NutrientGroup'),
        ),
        migrations.CreateModel(
            name='LinkNutrientFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('food', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='foods.Food')),
                ('nutrient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nutrients.Nutrient')),
            ],
        ),
    ]
