# Generated by Django 3.1.1 on 2020-10-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkNutrientNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MapNutrientCodeDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_code', models.IntegerField()),
                ('database', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrients.database')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='collapsedByDefault',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='familiarNameFr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nutrientgroup',
            name='nameEn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='NutrientTitle',
        ),
        migrations.AddField(
            model_name='mapnutrientcodedatabase',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='linknutrientnutrient',
            name='mom_nutrient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mom_nutrient', to='nutrients.nutrient'),
        ),
        migrations.AddField(
            model_name='linknutrientnutrient',
            name='son_nutrient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son_nutrient', to='nutrients.nutrient'),
        ),
    ]
