# Generated by Django 3.1.1 on 2020-12-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0002_auto_20201006_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=255)),
                ('category_name_fr', models.CharField(max_length=255)),
                ('category_name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='collapsedByDefault',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='besoinMax',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='max',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='menNeed',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='womenNeed',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='NutrientNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(default=1)),
                ('need', models.FloatField(default=0.0)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientCategoryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_fr', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrient')),
                ('nutrientCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrients.nutrientcategory')),
            ],
        ),
    ]
