# Generated by Django 3.1.1 on 2020-12-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0003_auto_20201217_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
