# Generated by Django 3.1.1 on 2020-12-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_nutrient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientcategory',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
