# Generated by Django 3.1.1 on 2020-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0005_nutrientcategory_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientneeds',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
