# Generated by Django 3.1.1 on 2020-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0006_nutrientneeds_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientneeds',
            name='code',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientneeds',
            name='sex',
            field=models.IntegerField(default=-1),
        ),
    ]
