# Generated by Django 2.2.4 on 2020-03-01 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conversion_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=149)),
                ('scrapped', models.BooleanField(default=False)),
                ('preparationTime', models.CharField(default='1h20', max_length=150)),
                ('difficulty', models.IntegerField(default=0)),
                ('imgUrl', models.URLField(default='https://assets.afcdn.com/recipe/20150901/59954_w420h344c1cx1500cy2250.jpg')),
                ('nutrientDensity', models.FloatField(default=0)),
                ('glycemicLoad', models.FloatField(default=20)),
                ('immuneSystemScore', models.FloatField(default=2)),
                ('testosteroneScore', models.FloatField(default=2)),
                ('bonesScore', models.FloatField(default=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link_meal_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='meal.Meal')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link_meal_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name_scrapped', models.CharField(default='', max_length=255)),
                ('quantity', models.FloatField(default=50)),
                ('conversion_factor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='foods.ConversionFactor')),
                ('food', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='foods.Food')),
                ('meal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='meal.Meal')),
            ],
        ),
    ]
