# Generated by Django 2.2.4 on 2020-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_meal_food',
            name='consumption_hour',
            field=models.IntegerField(default=-1),
        ),
    ]
