# Generated by Django 2.2.4 on 2020-05-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_remove_link_meal_food_consumption_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_meal_user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='link_meal_user',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='last_updated',
        ),
    ]
