# Generated by Django 2.2.4 on 2020-07-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_auto_20200515_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link_object_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=255)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Object_type')),
            ],
        ),
    ]
