# Generated by Django 2.2.4 on 2020-08-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_link_object_page_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMealMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom_meal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_meal', to='meal.Meal')),
                ('son_meal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son_meal', to='meal.Meal')),
            ],
        ),
    ]
