# Generated by Django 2.2.4 on 2020-08-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_linkmealmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='object_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='meal.Object_type'),
        ),
    ]
