# Generated by Django 3.1.1 on 2020-09-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_routinelinkmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinelinkmeal',
            name='meal_id',
        ),
        migrations.AddField(
            model_name='routinelinkmeal',
            name='linkMealMeal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.linkmealmeal'),
        ),
    ]
