# Generated by Django 3.1.1 on 2020-09-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_auto_20200916_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutineLinkMeal',
            new_name='LinkMealRoutineProp',
        ),
    ]
