# Generated by Django 3.1.1 on 2020-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_auto_20200916_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmealroutineprop',
            name='consumption_hour',
            field=models.FloatField(default=12),
        ),
    ]
